FROM php:7.4-apache
WORKDIR /var/www/html
COPY ./.docker/php/apache.conf /etc/apache2/sites-available/000-default.conf
COPY . /var/www/html
ENTRYPOINT [ "bash", "-c", "exec apache2-foreground" ]
EXPOSE 80
