name: Build and deploy

on:
  push:
    branches:
      - master
      - development

jobs:
  start:
    name: Variable setup
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.ref_branch.outputs.branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Reference branch
        id: ref_branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"

  build:
    name: Main
    runs-on: ubuntu-latest
    needs: start

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CI_SSH }}
          submodules: true

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.etv.tudelft.nl
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/php/Dockerfile.live
          push: true
          tags: docker-registry.etv.tudelft.nl/dies-2018:latest,docker-registry.etv.tudelft.nl/dies-2018:${{ needs.start.outputs.branch }}
